name: Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    needs: test
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17
      - name: Prepare environment
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          mkdir -p ~/.sbt/1.0
          touch ~/.sbt/1.0/sonatype.sbt
          echo "credentials += Credentials(Path.userHome / \".sbt\" / \"sonatype_credentials\")" > ~/.sbt/1.0/sonatype.sbt
          touch ~/.sbt/sonatype_credentials
          echo "realm=Sonatype Nexus Repository Manager" > ~/.sbt/sonatype_credentials
          echo "host=s01.oss.sonatype.org" >> ~/.sbt/sonatype_credentials
          echo "user=$SONATYPE_USERNAME" >> ~/.sbt/sonatype_credentials
          echo "password=$SONATYPE_PASSWORD" >> ~/.sbt/sonatype_credentials
      - name: Deploy
        run: sbt +publishSigned
      - name: Message
        run: echo "Staging repository created at https://s01.oss.sonatype.org/#stagingRepositories"