name: Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: sbt publishSigned